### ISSUE TITLE
The Implementation of FPConv+Rigid_KPConv

### ISSUE THREAD

**Issue by mutianxu** [lyqun/FPConv#12]
Dear Yiqun,

I'm a little confused about how you implement **FPConv+Rigid_KPConv**.

As you stated in Sec4.3 of the paper, Fig.7 is very clear for combining FPConv with Pointnet++ or PointConv. 
However, the statement of how you combining FPConv with KPConv is _"we have second fusion strategy by concatenating their output features in the last second layer of networks, an then applying a tiny network for fusion."_, which is a little bit confused for me.

Do you mean you parallel the **whole** KPConv network and the **whole** FPConv network and concatenate the output features in the last second layer of these two networks during training? Or if you just make some changes in Fig.7?

Due to this strategy gains the best performance in various tasks mentioned in your paper, it is meaningful if we can know the detailed implementation of this part.

I would also be highly appreciated if you could send me a simple figure to illustrate this part.

Thank you so much!

**Comment by lyqun** [comment]
Yes, as you mentioned, we parallel two models (KPConv and FPConv) and concatenate the output features in the last second layer, since they use different downsampling strategies (grid / voxel downsampling and FPS, respectively).

**Comment by mutianxu** [comment]
Thanks for your reply.

One more question, will this make the model be too large? E.g., large GPU memory usage or low speed when running this model?

Thanks a lot.

**Comment by lyqun** [comment]
Yes, fusion of FPConv and KPConv requires more GPU memory and time cost.

For you information,

we have also conducted comparsion experiments on fusion of convolution operators of same types and different types in our complementary, page 11.

![image](https://user-images.githubusercontent.com/22867481/94329299-6334f080-ffec-11ea-850c-a35eb07ed167.png)

**Comment by mutianxu** [comment]
Got it, thank you so much.
