### ISSUE TITLE
How many points used in ModelNet40 Classification task?

### ISSUE THREAD

**Issue by densechen** [lyqun/FPConv#17]
你好，我仔细阅读了你的论文，但是我们没有发现关于modelnet40实验上你们最终究竟是采用了多少个点作为输入呢？
这里可否方便告知一下，我们好加入对比算法中。
谢谢！

**Comment by lyqun** [comment]
Sorry for the late reply. 2048 points are used for classification on ModelNet40.

**Comment by densechen** [comment]
👌🏻
