### ISSUE TITLE
Pre-processed ScanNet v2 dataset Link

### ISSUE THREAD

**Issue by Sungmin-Woo** [lyqun/FPConv#18]
Hi @lyqun , thank you for sharing the codes!

I have tried to download the pre-processed ScanNet Dataset that you provided with Google Drive link, but it seems not available.
Can you check the link of ScanNet Dataset you provided in README?

**Comment by lyqun** [comment]
Thank you and I will update the link later.

**Comment by lyqun** [comment]
Sharing link is updated.
