### ISSUE TITLE
Pre-processed ScanNet v2 dataset  drive link require need a permission ?

### ISSUE THREAD

**Issue by giangdip2410** [lyqun/FPConv#21]
Thank you for your great working and sharing. But your pre-processed ScanNet v2 dataset  link need a permission to access ? Could you please share with me ? Thank you.

**Comment by lyqun** [comment]
I have tested the sharing link, and there is no problem. Please try again or show more details.

**Comment by giangdip2410** [comment]
thank you very much. I will check it again.

**Comment by giangdip2410** [comment]
@lyqun : I tried to download your link again but the message is still there. Could you please help me to check your pre-process Scannet v2 dataset link again ? Thank you very much

Permission denied: https://drive.google.com/uc?id=1xz59bKaIZbf0BU3oKSTs3qyV3gRf7aDW
Maybe you need to change permission over 'Anyone with the link'?

**Comment by lyqun** [comment]
Does the Google Drive show 'Blocked Third-party cookies can prevent Drive Web downloads' when you download the sharing file?

If so, you could follow the steps in [Download-a-file](https://support.google.com/drive/answer/2423534?hl=en#zippy=%2C%E9%98%BB%E6%AD%A2%E7%AC%AC%E4%B8%89%E6%96%B9-cookie-%E5%8F%AF%E8%83%BD%E4%BC%9A%E5%AF%BC%E8%87%B4%E6%97%A0%E6%B3%95%E9%80%9A%E8%BF%87%E7%BD%91%E9%A1%B5%E7%89%88%E4%BA%91%E7%AB%AF%E7%A1%AC%E7%9B%98%E4%B8%8B%E8%BD%BD%E5%86%85%E5%AE%B9%2Cblocked-third-party-cookies-can-prevent-drive-web-downloads).
