### ISSUE TITLE
config.json中没有‘scene_list’

### ISSUE THREAD

**Issue by MingyeXu** [lyqun/FPConv#3]
Traceback (most recent call last):
  File "tools/test_scannet.py", line 180, in <module>
    scene_list_dir=_cfg['scene_list'], 
KeyError: 'scene_list'

**Comment by MingyeXu** [comment]
> Traceback (most recent call last):
> File "tools/test_scannet.py", line 180, in
> scene_list_dir=_cfg['scene_list'],
> KeyError: 'scene_list'

**Comment by lyqun** [comment]
A quick solution is replacing `_cfg['scene_list']` by
```
'<path_to_this_repo>/utils/scannet_datalist/'
```

Thank you for pointing out, I will update later.
