### ISSUE TITLE
hi,can you provide me with pointnet2_ cuda's source file?

### ISSUE THREAD

**Issue by genius-lu** [lyqun/FPConv#6]
I always fail to install with PIP in the same environment. As a result, I can't reproduce your experiment. I don't know you can provide a copy of pointnet2_ cuda's source file, thank you very much

**Comment by lyqun** [comment]
Did you encounter any errors when installing pointnet2 by running
```
cd fpconv/pointnet2
python setup.py install
cd ../
```

**Comment by genius-lu** [comment]
Thank you for your reply. I did try this instruction according to readme at that time. It shows that VC 14.0 is missing, but I have already installed VC 2015. For pointnet2, this large package is already available on GitHub, but the pointnet2-cuda package invoked in pointnet2-untils can never be found. I see that you seem to have compiled this package in C. I don't know if you have Python compiled source files

**Comment by lyqun** [comment]
Sorry, we have not tested the environment on Windows yet. If you are insterested in this package, you could refer to this repo [sshaoshuai/Pointnet2.Pytorch](https://github.com/sshaoshuai/Pointnet2.PyTorch) for solution.

**Comment by genius-lu** [comment]
I will try to run this experiment on Linux . Thank you very much for your answer
