### ISSUE TITLE
can not download scannet?

### ISSUE THREAD

**Issue by longmalongma** [lyqun/FPConv#8]
Are these the only files  _vh_clean_2.ply and _vh_clean_2.labels.ply  you need to download to download the original Scannet dataset?This data set is too big to download

**Comment by lyqun** [comment]
Yes, only _vh_clean_2.ply and _vh_clean_2.labels.ply are used for data pre-processing.

Actually, we also provide a pre-processed ScanNet dataset used only for this repo, which you could download from Google Drive (please refer to README).

**Comment by longmalongma** [comment]
How big they are？





------------------ Original ------------------

**Comment by lyqun** [comment]
9 GB totally for preprocessed pickles (3 files for train, eval and test splits).

About 20 GB (or maybe larger) for the official dataset ( _vh_clean_2.ply and _vh_clean_2.labels.ply only).

**Comment by longmalongma** [comment]
> _vh_clean_2.ply and _vh_clean_2.labels.ply

Thanks for your reply!
